// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using librarycompany.Context;

#nullable disable

namespace librarycompany.Migrations
{
    [DbContext(typeof(ApplicationDbcontext))]
    partial class ApplicationDbcontextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("librarycompany.Models.Author", b =>
                {
                    b.Property<int>("AuthorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AuthorId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nationality")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("notableworks")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AuthorId");

                    b.ToTable("Authors");
                });

            modelBuilder.Entity("librarycompany.Models.Book", b =>
                {
                    b.Property<int>("ISBN")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ISBN"));

                    b.Property<int>("AuthorID")
                        .HasColumnType("int");

                    b.Property<int?>("TransactionId")
                        .HasColumnType("int");

                    b.Property<string>("author")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("avastatus")
                        .HasColumnType("int");

                    b.Property<int>("branchid")
                        .HasColumnType("int");

                    b.Property<int>("genr")
                        .HasColumnType("int");

                    b.Property<int>("publicationyear")
                        .HasColumnType("int");

                    b.Property<int>("publich")
                        .HasColumnType("int");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ISBN");

                    b.HasIndex("AuthorID");

                    b.HasIndex("TransactionId");

                    b.HasIndex("branchid");

                    b.HasIndex("genr");

                    b.HasIndex("publich");

                    b.ToTable("Books");
                });

            modelBuilder.Entity("librarycompany.Models.Branche", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("city")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("street")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Branches");
                });

            modelBuilder.Entity("librarycompany.Models.Contact", b =>
                {
                    b.Property<int>("ContactId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ContactId"));

                    b.Property<int>("branchbookid")
                        .HasColumnType("int");

                    b.Property<int>("memberid")
                        .HasColumnType("int");

                    b.Property<int>("phonenumber")
                        .HasColumnType("int");

                    b.Property<int>("publich")
                        .HasColumnType("int");

                    b.Property<int>("staffid")
                        .HasColumnType("int");

                    b.HasKey("ContactId");

                    b.HasIndex("branchbookid");

                    b.HasIndex("memberid");

                    b.HasIndex("publich");

                    b.HasIndex("staffid");

                    b.ToTable("Contacts");
                });

            modelBuilder.Entity("librarycompany.Models.Genre", b =>
                {
                    b.Property<int>("GenreId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GenreId"));

                    b.Property<string>("GenreTypename")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("GenreId");

                    b.ToTable("Genres");
                });

            modelBuilder.Entity("librarycompany.Models.Member", b =>
                {
                    b.Property<int>("MembershipId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MembershipId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("city")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("mtype")
                        .HasColumnType("int");

                    b.Property<string>("street")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MembershipId");

                    b.ToTable("Members");
                });

            modelBuilder.Entity("librarycompany.Models.Publisher", b =>
                {
                    b.Property<int>("publisherID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("publisherID"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("publisherID");

                    b.ToTable("Publishers");
                });

            modelBuilder.Entity("librarycompany.Models.Staff", b =>
                {
                    b.Property<int>("StaffID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StaffID"));

                    b.Property<string>("StaffName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("branchid")
                        .HasColumnType("int");

                    b.Property<string>("position")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("StaffID");

                    b.HasIndex("branchid");

                    b.ToTable("Staffs");
                });

            modelBuilder.Entity("librarycompany.Models.Transaction", b =>
                {
                    b.Property<int>("TranscationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TranscationID"));

                    b.Property<string>("borrowedbook")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("duedate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("fine")
                        .HasColumnType("int");

                    b.Property<int?>("memberid")
                        .HasColumnType("int");

                    b.Property<string>("penalties")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TranscationID");

                    b.HasIndex("memberid");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("librarycompany.Models.Book", b =>
                {
                    b.HasOne("librarycompany.Models.Author", "Author")
                        .WithMany("Authorbook")
                        .HasForeignKey("AuthorID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("librarycompany.Models.Transaction", "Transaction")
                        .WithMany("BorrowedBooks")
                        .HasForeignKey("TransactionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("librarycompany.Models.Branche", "Branch")
                        .WithMany("branchbooks")
                        .HasForeignKey("branchid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("librarycompany.Models.Genre", "Genre")
                        .WithMany("Generhbook")
                        .HasForeignKey("genr")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("librarycompany.Models.Publisher", "Publisher")
                        .WithMany("publichbook")
                        .HasForeignKey("publich")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("Branch");

                    b.Navigation("Genre");

                    b.Navigation("Publisher");

                    b.Navigation("Transaction");
                });

            modelBuilder.Entity("librarycompany.Models.Contact", b =>
                {
                    b.HasOne("librarycompany.Models.Branche", "Branch")
                        .WithMany("contacts")
                        .HasForeignKey("branchbookid")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("librarycompany.Models.Member", "Member")
                        .WithMany("contacts")
                        .HasForeignKey("memberid")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("librarycompany.Models.Publisher", "Publisher")
                        .WithMany("contacts")
                        .HasForeignKey("publich")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("librarycompany.Models.Staff", "Staff")
                        .WithMany("contacts")
                        .HasForeignKey("staffid")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Branch");

                    b.Navigation("Member");

                    b.Navigation("Publisher");

                    b.Navigation("Staff");
                });

            modelBuilder.Entity("librarycompany.Models.Staff", b =>
                {
                    b.HasOne("librarycompany.Models.Branche", "Branch")
                        .WithMany("branchstaff")
                        .HasForeignKey("branchid")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Branch");
                });

            modelBuilder.Entity("librarycompany.Models.Transaction", b =>
                {
                    b.HasOne("librarycompany.Models.Member", "Member")
                        .WithMany("transactionbook")
                        .HasForeignKey("memberid");

                    b.Navigation("Member");
                });

            modelBuilder.Entity("librarycompany.Models.Author", b =>
                {
                    b.Navigation("Authorbook");
                });

            modelBuilder.Entity("librarycompany.Models.Branche", b =>
                {
                    b.Navigation("branchbooks");

                    b.Navigation("branchstaff");

                    b.Navigation("contacts");
                });

            modelBuilder.Entity("librarycompany.Models.Genre", b =>
                {
                    b.Navigation("Generhbook");
                });

            modelBuilder.Entity("librarycompany.Models.Member", b =>
                {
                    b.Navigation("contacts");

                    b.Navigation("transactionbook");
                });

            modelBuilder.Entity("librarycompany.Models.Publisher", b =>
                {
                    b.Navigation("contacts");

                    b.Navigation("publichbook");
                });

            modelBuilder.Entity("librarycompany.Models.Staff", b =>
                {
                    b.Navigation("contacts");
                });

            modelBuilder.Entity("librarycompany.Models.Transaction", b =>
                {
                    b.Navigation("BorrowedBooks");
                });
#pragma warning restore 612, 618
        }
    }
}
